apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: space-viktorious01
  namespace: argocd
spec:
  destination:
    name: 'sa-tanzu-platform:EMEA:space:space-viktorious01'
    namespace: default
    server: ''
  source:
    directory:
      recurse: true
    path: gitops/emea/spaces/space-viktorious01
    repoURL: 'https://github.com/viktoriousss/argocd-tanzu-platform'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - Validate=false
    automated:
      prune: false
      selfHeal: false
